# Generated by Django 4.2.13 on 2024-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
    ]
