# Generated by Django 5.0.6 on 2024-06-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0008_alter_profissional_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
