# Generated by Django 5.0.4 on 2024-06-26 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0012_profissionalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categorias', models.CharField(max_length=255)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ServicoUsuario',
        ),
        migrations.AlterField(
            model_name='profissionalprofile',
            name='categorias',
            field=models.CharField(max_length=100),
        ),
    ]
