# Generated by Django 5.0.4 on 2024-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0013_servico_delete_servicousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='solicitante',
            field=models.CharField(max_length=255),
        ),
    ]
