# Generated by Django 5.0.6 on 2024-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0014_alter_servico_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='categorias',
        ),
        migrations.AddField(
            model_name='servico',
            name='categorias',
            field=models.ManyToManyField(to='works365.categoria'),
        ),
    ]
