# Generated by Django 5.0.4 on 2024-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0015_categoria_remove_servico_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
