# Generated by Django 5.0.6 on 2024-06-27 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0016_servico_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='works365.userprofile'),
            preserve_default=False,
        ),
    ]
